version: 0.2

phases:
  install:
    commands:
      - echo Executing Install Phase
  pre_build:
    commands:
      - echo Executing Pre Build Phase
      - java -version
      - mvn -version
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI = 716945757783.dkr.ecr.us-east-1.amazonaws.com/aws-rnralbumart-ecr-repository
      - COMMIT_HASH = $(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Executing Build Phase
      - echo Building the Docker image ...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Executing Post Build Phase
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"rnralbumart","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - target/rnralbumart.jar
    - imagedefinitions.json
