version: 0.2

phases:
  install:
    commands:
      - echo Executing Install Phase
  pre_build:
    commands:
      - echo Executing Pre Build Phase
      - echo java -version
      - echo mvn -version
  build:
    commands:
      - echo Executing Build Phase
      - mvn clean package
  post_build:
    commands:
      - echo Executing Post Build Phase
artifacts:
  files:
    - target/rnralbumart.jar
